### ISSUE TITLE
User settings: Enable full tabbed layout capability

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1459]
## Description

As a user I want to be able to manage all aspects of my profile

## Acceptance criteria

- [ ] Able to manage communities
- [ ] able to manage organizations
- [ ] admin management also tabbed
