### ISSUE TITLE
UX: Usability gaps addressed

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1537]
## Description

As a user I want a consistent and polished user experience

## Acceptance criteria

- [ ] Footer bar redesigned
- [ ] Home page layout v1
- [ ] Challenge Explorer layout
- [ ] Contributors Explorer
