### ISSUE TITLE
User interactions should only trigger error responses on errors

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1650]
## Description
For effective platform monitoring, an error should really be something to be investigated + reported on. At the moment we generate many errors from normal interaction that makes it hard to see what the real errors are.

## Initiative / goal
Effective platform monitoring.

### Hypothesis
By removing errors that occur during normal interactions, using our default Web Client, we can much easier see when real problems are happening on the platform.

Interactions that happen outside of the normal web client are minimal at the moment. 

## Acceptance criteria and must have scope
- [ ] Non-authenticated users have no errors
- [ ] Simple registered users have no errors
- [ ] Use authorization=>myPrivileges to avoid making calls (eg. users() ) that are not needed 
- [ ] No red icons on the graphql calls!

Flows to cover:
- Landing page
- Public hub page + navigating to community tab
- Private hub page
- Challenge in public hub + navigating to community tab
- Opportunity in public hub
- User profile
- Organization profile

## Stakeholders
As a user I should not be making requests that I know will give errors
As a platform administrator I want to be able to see when real errors are occurring where I need to take action. 
As a release manager I want to be able to effectively monitor what happens after a new release. 

## Timeline
Q2 2022

## Additional Context
Install https://chrome.google.com/webstore/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln/related?hl=en-GB

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/59727934-02cb-4d35-bf8c-7b569fb9ad6e)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/04c7372a-a6e6-4cf1-9f53-f639b1921e71)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/fd59135b-b1e2-4a54-8df1-92e1cfd345a2)

**Comment by techsmyth** [comment]
Closing in favor of root cause analysis epic
