### ISSUE TITLE
Use public api end point for obtaining configuration and meta-data

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1655]
## Description

As a client I want to be able to deal with requests specifying a cookie that is not valid

## Acceptance criteria

- [ ] Retrieving of the configuration and meta-data from the server to use the public api end point 
- [ ] Usage of the metadata to be from the meta-data provider and not apollo
- [ ] Public Graphql Endpoint ---> env.REACT_APP_ALKEMIO_DOMAIN + '/api/public/graphql';
- [ ] Private Graphql Endpoint ---> env.REACT_APP_ALKEMIO_DOMAIN + '/api/private/graphql';
