### ISSUE TITLE
UX: Admin tabbed across application

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#1726]
## Description

As a user I want a consistent administration across the platform

## Acceptance criteria

- [ ] Administration of Hubs, Challengs, Opportunities should have a tabbed layout similar to that of a User profile
- [ ] Administration of Users to allow seeing the full set of tabs for a user and not just the profile tab
- [ ] Administration of Organizations to move to a tabbed layout

## Additional Context
Current design with initial tabs as mentioned in Miro board below
https://xd.adobe.com/view/450cbff7-db30-4605-82ba-b1a206944fd4-105f/

New design for the admin "landingpage" as mentioned in Neil's comment
https://xd.adobe.com/view/4619358f-3203-401a-a44f-0ed50c6c47f8-134a/
