### ISSUE TITLE
Aspects++

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#1926]
## Description
As an community manager I want Aspects to be personalized, to be able to see who created it. 
As an community manager I want  to be able to search for a person and see which aspects they created. 

## Acceptance criteria 
- [ ] User that created the aspect is visible on the card
- [ ] Authorization model refined
- [ ] Deleting of aspects
- [ ] Make UX Design
- [ ] ... 

## Stakeholders
UWV

**Comment by techsmyth** [comment]
Split remaining work re tagline, search to a new Epic to be prioritized separately.
