### ISSUE TITLE
Home Page refresh

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#1927]
## Description
As a user I want to see the content that is relevant to me, while still being able to engage
more with Alkemio

## Initiative / goal
Keep users more actively engaged on the platform
Allow users to quicker orientate + know what they can do

### Hypothesis
Users should more quickly be able to get to relevant content, and be guided on how to start

## Acceptance criteria and must have scope
- [ ] Top section of the home page to differ depending on whether the user is logged in or not
- [ ] For logged in users (a) show the hubs they are a member off at the top + pinned separately (b) show a personalized message + prompt if needed to fill out their profile
- [ ] Updated footer section to help users find additional information
- [ ] Feedback from stakeholders

Design:
https://xd.adobe.com/view/efc89673-a108-4b16-9306-9881714b228e-ba9b/

## Stakeholders
All partner community managers

## Timeline
Bulk in sprint ending July 4th approx
