### ISSUE TITLE
Improve user experience around logins / sessions 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2092]
## Description
Users are used to a very high quality level of platform interactions. Any blockers or other impediments to them engaging effectively dramatically increases the chance of them not engaging fully.

## Initiative / goal
Ensure that the on-boarding and usage experience for users is optimized. 
Engage the users with the platform.

### Hypothesis
We are currently losing potential users due to the issues listed here.

## Acceptance criteria and must have scope
- [ ] User sessions extended past token lifetime
- [ ] If the users session cannot be extended, inform the user and prompt to login again (remember where they were, see point 3 below!)
- [ ] Client to remember where the user wants to go + bring the user there after login

## Stakeholders
Partner community managers
User community

As a user I expect the client to inform me when my token has expired and prompt me to login
As a user I expect that when I try to access a restricted page and get prompted to login that the client remembers where I was going + brings me there

## Timeline
End Q2
