### ISSUE TITLE
Administration of AspectTemplates for Hubs

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2109]
## Description

As a Hub admin I want to be able to manage the set of Aspect Templates that are in use in my Hub

## Acceptance criteria

- [ ] Admin UX for Hubs to have a new tab: Templates
- [ ] Templates tab to show details of the Aspect Types that are used as per design
- [ ] Pop up to show details of the Aspect Type template, allow updating and deletion
- [ ] New button to allow creation of new Aspect Type templates

Note: the UX design is missing a field for providing the defaultDescription, that needs to be added in
Note: no Explore templates button for now

## Additional Context
https://xd.adobe.com/view/e06dcac1-f20c-4bf4-9b69-12cf76b17a99-b53e/

**Comment by Comoque1** [comment]
Tested on DEV env.
Looks as per design.

A couple of bugs raised regarding behavior:
- [ ] BUG: When admin is on "templates" tab and clicks on any other tab (i.e. "challanges") tab, he is redirected to 404 page #2232 - **urgent**
- [ ] BUG: When template with long type name is created, its display on "Contribute" panel is cut on both sides #2235
- [ ] BUG: Initial state of "Create" button for aspect templates is "enabled", instead of disabled #2234
- [ ] BUG: When user create a aspect template, the state of "Create" button doesn't update immediately after event #2233
- [ ] BUG: Aspect template overview doesn't render image from MD #2231
