### ISSUE TITLE
Visibility of Groups

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2308]
## Description

Currently, we only display groups on the admin side. They are not yet visible on the client side, but we see a need that this is a functionality that customers want to use, such as UWV. 

## Initiative / goal

Make these groups visible on the client as well

### Hypothesis

Stakeholders need groups to visualize to their uses what the role or expertise is of each user within the challenges that they work on at the platform. 

## Acceptance criteria and must have scope

- [ ] Design for visibility groups on the user profile page
- [ ] Design for visibility groups within the community of hubs/challenges/opportunities
- [ ] Design for individual user to manage their groups

## Stakeholders

Requested by UWV for the accelerator programs they will host on Alkemio

## Timeline

Accelerator will start the 1st of september
