### ISSUE TITLE
Suggested images for Visual

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2337]
## Description
As a user I want to be easily able to find images for the banners on my entities
As a compliance officer I want to ensure that the images being offered are under a valid license

## Acceptance criteria
- [ ] Users to be presented with the option to "find" relevant images to be associated with a given entity via some terms (tags, title etc). 
- [ ] Images have be be sourced from a creative commons licensed repository
- [ ] Images sourced based on the fields from the parent entity: displayName, tagline, context / description 
- [ ] Default options as well for avatars

**Comment by techsmyth** [comment]
Moving to icebox as with the launch to Unsplash for users we have already reduced the hurdle significantly.

**Comment by SimoneZaza** [comment]
part of #601
