### ISSUE TITLE
Search: UX refresh

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#2338]
## Description
As a user I want that the search experience matches the rest of the platform UX

## Acceptance criteria
- [ ] Two sections for search results: challenges / opportunities, contributors
- [ ] Search interface upgraded to match the rest of the platform UX
- [ ] New search Card for Organizations to match the design of other cards
- [ ] Each search results section to return 10 entries, and this to be displayed on text on screen
- [ ] Search button in top menu bar

## Additional Context
https://www.figma.com/file/bkCWN7FiPzFVwmO6SUoYBF/Search-refresh?node-id=2%3A1520

**Comment by techsmyth** [comment]
@larssondenise @SimoneZaza @ccanos to decide what happens on hover / click. That is not clear at the moment from the design.
