### ISSUE TITLE
Wysiwyg editing

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/client-web#2758]
## Description
We are currently using text editor that supports markdown but looks very scary to the average user...

## Initiative / goal

Simplify the rich text editor to make it easy and engaging

### Hypothesis

The platform experience and usability of each user will be improved

## Acceptance criteria and must have scope
- [ ] Search for rich text editor components that can be plugged in
- [ ] Choose the component and remove unnecessary/overcomplicating tools
- [ ] Explore the ability to upload documents / images
