### ISSUE TITLE
Innovation pack profile: add collaboration tool templates

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#4629]
## Description

As a user, I want to see the different collaboration tool templates that are in an innovation pack
As an innovation pack admin, I want to manage my ct-templates

### Innovation Pack Profile page
- [ ] CT-templates block above the whiteboards block, same styling etc as other blocks
      - [ ] Title: Templates for Collaboration Tools (<amount>)
      - [ ] Cards from issue #4630 
- [ ] Preview dialog from #4634

### Innovation Pack Profile settings page
- [ ] CT-templates block above the whiteboards block, same styling etc as other blocks with create new button
     - [ ] Cards from issue #4630
- [ ] Change cards in other blocks to also be the same as in the user view of the profile page, the "normal" cards, not these very old ones. 
- [ ] Create/Edit dialog from issue #4632
- When admin clicks on create, empty create/edit dialog is opened
- When admin clicks on card, pre-filled edit dialog is opened

## Additional Context

Screen shots / UX designs / data that are relevant.
