### ISSUE TITLE
QA: Test suite user authentication flows

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#4771]
## Description
A test suite covering expected user interaction scenarios

## Initiative / goal
Quality experience for users

### Hypothesis
A robust test suite covering user identity related flows is critical to avoid any issues with users being able to login

## Acceptance criteria and must have scope
- [ ] Defined scenarios for user authentication and redirects, including a) bringing the user back to where they started b) interaction with custom home pages c) interaction with landing page
- [ ] Test scenarios automated via the browser (to discuss what this means)
- [ ] Test scenarios executable in the following builds: tbd

## Stakeholders

Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline

What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design

Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
