### ISSUE TITLE
My Dashboard: Authorized user, no memberships

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5005]
## Description

As an authorized user without any Space memberships, I want to have an engaging dashboard with a clear indication of what to do

### Body left column
- [ ] Platform news banner #5010
- [ ] Become a member block #5021
- [ ] Explore other challenges block #5015
- [ ] Starting a Space Banner #5016

### Body right column
- [ ] Tips & Tricks block #5013
- [ ] Innovation library block #5014
- [ ] Latest contributions to the forum #5019 **to show as many as needed to make the two columns to be of the same** length

### Body full-width bottom section 
- [ ] More about Alkemio block #5017

### Mobile
- [ ] First left column
- [ ] Then right column
- [ ] Then bottom section

## Additional Context

Figma: 
https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=548%3A13179&mode=design&t=7QvL3jIfZJWu0HvX-1
