### ISSUE TITLE
My Dashboard: Authorized user with memberships

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5006]
## Description

As an authorized user with Space memberships, I want to be able to jump in directly where I left off, see all the things that are happening in the spaces that I'm a member of, be prompted about open invitations, etc.

### Body top section
- [ ] List of Spaces #5009

### Body left column
- [ ] Platform news banner #5010
- [ ] Left: New memberships block #5011
- [ ] Right: My latest contributions block #5012
- [ ] Left: Tips & Tricks block #5013
- [ ] Right: Innovation library block #5014
- [ ] Explore other challenges block #5015
- [ ] Starting a Space Banner #5016
- [ ] More about Alkemio block #5017

### Body right column
- [ ] Latest Contributions in my Spaces block #5018 **to show as many as needed to make the two columns to be of the same length**
- [ ] Latest contributions to the forum #5019 **3 entries**

### Mobile
- [ ] First top section (list of spaces)
- [ ] Then **right** column
- [ ] Then left column

## Additional Context

Figma: 
https://www.figma.com/file/noZ6QjMORE2nNkhccSc9pG/Homepage?type=design&node-id=548%3A13179&mode=design&t=7QvL3jIfZJWu0HvX-1

**Comment by Comoque1** [comment]
The findings are as follows:
- [ ] `Tips & Tricks` and `Innovation Library` blocks are on separate rows instead of on the same.
- [ ] `Become a member` but is not defined in the list above
- [ ] On Mobile, it shows the left columns before the right, and "More about Alkemio" is in the middle, but should be on bottom in my opinion
