### ISSUE TITLE
UX: Accessibility++

### ISSUE THREAD

**Issue by atstoyanov** [alkem-io/client-web#516]
## Description
To reach wider range of users we must comply with the requirements for accessibility. The topic is huge and important part of every modern application. 

https://www.w3.org/standards/webdesign/accessibility

## Initiative / goal
The goal is to improve our working process to include the accessibility in the mind of developers and QAs.

## Acceptance criteria and must have scope
- [ ] Current stage of the web UI is updated to include possible accessibility options.
- [ ] Definition of done includes the accessibility check.
- [ ] QA/Test include accessibility testing.

## Stakeholders

Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline

What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.
