### ISSUE TITLE
Spaces page (former Challenges page)

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#5739]
## Description

As a user I want to explore all Spaces
As a user I want a place were spaces "live" to conceptually better understand the platform

## Acceptance criteria

- [ ] Update header text and icon as per design
- [ ] Spaces page to have 1 blocks: Explore Spaces
- [ ] Block to have title, explanation/description, search/filterbar, and (sub)space cards (#5742)
- [ ] Search bar on the left, to use as many space as there is available
- [ ] Search to be triggered with return key or by clicking on search icon
- [ ] Filter buttons on the right to be mutually exclusive (only one can be selected at a time)
- [ ] Mobile: 2 rows: search on top, filters below
- [ ] Public/Private/Member labels on cards visible when filtering on All Spaces
- [ ] No labels on cards visible when filtering on Member Spaces
- [ ] My Space labels visible when filtering on Public Spaces
- [ ] When there are no memberships in the blocks (or the user isn't authenticated), show text as per design on the right in the figma file, with the text linking to the sign in page
- [ ] Expand button to expand the block to show all, paginated on scroll

## Additional Context

- We need a server side search for this, not part of this issue
- Spaces have to come from the server sorted on most recent activity

Design: https://www.figma.com/file/pxOFKM0Rc8Mp2xIspCMU8k/Explore-Challenges?type=design&node-id=15%3A12773&mode=design&t=FXGaBcGzBZt7Fmuo-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by Comoque1** [comment]
These are the finding from testing on DEV env:
- [ ] Update header text and icon as per design - **OK**
- [ ] Spaces page to have 1 blocks: Explore Spaces - **OK**
- [ ] Block to have title, explanation/description, search/filterbar, and (sub)space cards (#5742) **- OK**
- [ ] Search bar on the left, to use as many space as there is available **- OK**
- [ ] Search to be triggered with return key or by clicking on search icon **- OK** 
- [ ] Filter buttons on the right to be mutually exclusive (only one can be selected at a time)**- OK**
- [ ] Mobile: 2 rows: search on top, filters below - search is not on top + 1 bug: #5875
- [ ] Public/Private/Member labels on cards visible when filtering on All Spaces**- OK**
- [ ] No labels on cards visible when filtering on Member Spaces**- OK**
- [ ] My Space labels visible when filtering on Public Spaces
- [ ] When there are no memberships in the blocks (or the user isn't authenticated), show text as per design on the right in the figma file, with the text linking to the sign in page - this does not seem to be fully implemented
   - [ ] for unauthenticated user: the text is missing
   - [ ] there is no linking to sign in page for both unauthenticated and user without members
   - [ ] text: `You’re not currently a member of any Space. Click **here** to visit our Welcome @ Alkemio Space, which is a fantastic starting point for your journey on Alkemio!` missing URL 

- [ ] Expand button to expand the block to show all, paginated on scroll - there is no expand button, the pagination is in place
- [ ] 

In Addition: 
- [ ] errors are thrown for users with no membership to private spaces
<img width="1472" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEpMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6d6942ee180384bfdb147fcdeb6aa6ddfba72872/image.png" alt="image.png" />

- [ ] The page takes around 4 sacond to load on DEV env, as 10 Spaces and challenges, but in reality, more data is requested, which results in slow visualization on the page
<img width="1394" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f4d29a5f1bd6884d96798d38c9a346c530c9c4b/image.png" alt="image.png" />


- [ ] Tags are not displayed on the cards, but are returned from the requested spaces/challenges
  <img width="1523" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXBMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20d31ea6a2f96d8bebc9961316d88da636088511/image.png" alt="image.png" />

- [ ] On the cards on expand, context/vision is displayed, is it a requirement?
<img width="1365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkpMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98bb9ee02c11f4c1114be0d6c13a5513e7d81eed/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
Spaces page is crashing, which prevents testing of the above comments:
[Uploading... image.png]

**Comment by bobbykolev** [comment]
> Spaces page is crashing, which prevents testing of the above comments: [Uploading... image.png]

The following fix enables back the testing of the Spaces page:
https://github.com/alkem-io/client-web/issues/5970

**Comment by Comoque1** [comment]
Raised one minor bug, the rest seems OK.
https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/6156
