### ISSUE TITLE
Notifications instances

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#6292]
## Description

As a platform user, I want to see all notifications in a consistent way

## Acceptance criteria
All notifications are composed from the same basic structure:
- [ ] Left: Journey avatar with User avatar on top of it, somewhat like a badge (See design).  > clicking on the avatar opens the related content (journey page or user profile)
- If there is no user avatar, only show Journey avatar
- If there is no Journey avatar (eg with personal message), User avatar becomes the big avatar
- [ ] Center: title > clicking in this area opens the related content (#6293)
- [ ] Center: preview > clicking in this area opens the related content (#6293)
- [ ] Right: time indicator like the one we use in the activity logs
- [ ] Right: menu
- Mark as read/unread > mark as read/unread
- Delete notification > delete
- Notification settings > open notification settings page
- [ ] Right: unread indicator
- [ ] Bottom left: Breadcrumb
- [ ] Bottom right: Button (not always there) (#6293)
- [ ] Full: Unread notifications to have a "light" (#DEEFF6) background, read notifications a white background 

## Additional Context
- Design: https://www.figma.com/design/pRGFSyng0dxovpvlaWGI8t/Notifications?node-id=319-8082&t=Kyb4zUf7K1dhd1vy-1

## Areas that will be affected 
 
_To be added during the refinement_
