### ISSUE TITLE
Simple homepage: Complete page Space view

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7038]
## Description

As a user who starts using Alkemio as part of the VC Campaign (or any other future campaign), I expect to see something about the VCs directly

## Acceptance criteria
Use the ACs to check the correct order of the blocks. All items are extracted in other stories.

- [ ] Left: menu from #7033
- [ ] Right when no memberships: 
  - [ ] Invitation block(s) when there is/are open invitation(s)
  - [ ] Campaign block from #7037 if user is authorized as beta tester / vc campaign
  - [ ] Explore spaces block that is also used on dashboard for unauthenticated users (#6943) > we may need to tweak this a little bit with respect to the filters
  - Figma: https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=344-413&t=58RTC3BT0xgKmyW1-1
- [ ] Right when memberships: 
  - [ ] Platform updates banner
  - [ ] Campaign block from #7037 if user is authorized as beta tester / vc campaign
  - [ ] Space blocks from #7035, ordered by last seen (or latest activity, whichever is easier) 
  - Figma: https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=344-1199&t=58RTC3BT0xgKmyW1-1

## Additional Context
<img width="777" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHROQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ef4d0bb2719f736989bcf31d4739ecbd2c719a7/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_
