### ISSUE TITLE
Simple homepage: Complete page Activity view

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/client-web#7054]
## Description
As a power user, I want to have a direct overview of all activity when I go to my homepage

## Acceptance criteria

- [ ] [ ] Left: 
  - [ ] Menu from #7033
  - [ ] If the user is hosting resources #7077
- [ ] Right:
  - [x] Platform update 
  - [x] Campaign block (VC, separate story)
  - [ ] **Horizontal memberships list as in current dashboard** (rework required)
  - [ ] Latest activity in my spaces (left) (same as on current dashboard, or from #7034)
  - [ ] My latest activity (right) (#7034 but in block instead of dialog)

## Additional Context
Figma: https://www.figma.com/design/kA1NFl2zU8CdiIbdvuzRTk/Alkemio-Home-Page?node-id=344-2305&t=58RTC3BT0xgKmyW1-1
<img width="810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2xaQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d84e92f8224fbac03fd8f739645f6196c3713fb1/image.png" alt="image.png" />

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by bobbykolev** [comment]
The estimate is based on everything already developed and just ordering the layout + some component switching and testing different scenarios.
