### ISSUE TITLE
Migration roadmap to Material

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#891]
## Description

As a developer I want a clear set of component libraries that are in use so that it is clear what the components options are

## Acceptance criteria
- [x] List of components currently based on Bootstrap that need to be migrated, with a small / medium / large sizing for each
- [x] List of additional componentisation issues that should be carried out
- [x] Implications for icons / branding?
- [ ] The application retains its look and feel

Results: https://hackmd.io/urb7zvcMQ7SnOaVM7naV0Q

## Additional Context
Which migrations should be done now?
