### ISSUE TITLE
Last modified visible for Opportunity, Challenges

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/client-web#958]
## Description

As a user I want to know which opportunities or challenges recently had updates. 

## Acceptance criteria

- [ ] Challenges + Opportunities should have an api visible field for "last modified". This is likely separate from the database level "last modified".
- [ ] The field should be updated on the following events: Editing the Context information; Adding a new reference; Updating Tags; adding a new child item (e.g. Opportunity for Challenge)
- [ ] The UI should display this field on the cards for challenges on the ecoverse page, and on the cards for opportunities on the challenge page
.... ** to be refined further **

## Additional Context

"I would love to have a "last updated" date on the opportunities page. So people can see how up-to-date the information is. And it would also be great to show it on the opportunities overview page. Like they are doing here: https://www.winnovatie.nl/innovaties"
